#:schema node_modules/wrangler/config-schema.json
name = "minecraft-banner"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

rules = [
  { type = "Data", globs = ["**/*.ttf"], fallthrough = true },
  { type = "Data", globs = ["**/*.woff"], fallthrough = true },
  { type = "Data", globs = ["**/*.woff2"], fallthrough = true },
  { type = "Data", globs = ["**/*.webp"], fallthrough = true },
  { type = "Text", globs = ["**/*.html"], fallthrough = true }
]